name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: |
          npm install
      - name: Build and test
        run: |
          expo build:android
          expo build:ios
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-builds
          path: |
            ./android/app/build/outputs/apk/release/app-release.apk
            ./ios/build/Build/Products/Release-iphoneos/*.ipa
